# Generated by Django 4.2.1 on 2023-11-28 19:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ExamInterface', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_category',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
